### ISSUE TITLE
Parser Cleanup Meta-Issue

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/michelson-semantics#48]
- [ ] Remove unused syntactic categories
- [ ] In most syntactic names, rename `contract` to `script` because Michelson community refers to Michelson programs as scripts
- [ ] Make documentation/code more consistent when talking about different syntactic levels:
  1. Michelson extended syntax with macros
  2. Michelson core syntax
  3. K-Michelson implementation syntax
  4. Micheline (if needed)
- [ ] (possibly) First parse into a Micheline representation and then check Michelson
- [ ] (possibly) Find a way to properly parse `PAIR` and `UNPAIR` macros
- [ ] (possibly) Parse annotations into some structure to be used during type checking/evaluation

**Comment by sskeirik** [comment]
Another task is to clean-up parsing of `key`, `key_hash`, `address`, `signature`, and `chain_id` literals. They are (except `chain_id`) specified using a base58check encoding with particular prefixes depending on the key types. See more notes below:

Overall:
- byte size and encoded size available at end of 'tezos/src/lib_crypto/base58.ml'
- alternate simpler implementation available in pytezos at 'pytezos/crypto.py'
- Tezos shows keys
- checksum bytes are generated used SHA256 x 2

Public Key Representation in Tezos:
- uses point compression: see
  - general desc - https://cryptopp.com/wiki/Point_Compression
  - Tezos compression - https://tezos.stackexchange.com/a/623/309

Public Key Hash:
- public key hash uses Blake2b with digest size 20 to generate hash

Chain Id:
- chain_id is a four-byte value

Ed25519:
let () = Base58.check_encoded_prefix Public_key_hash.b58check_encoding "tz1" 36
let () = Base58.check_encoded_prefix b58check_encoding "edpk" 54
let () = Base58.check_encoded_prefix b58check_encoding "edsk" 54 ;
let () = Base58.check_encoded_prefix b58check_encoding "edsig" 99

Secp256k1:
let () = Base58.check_encoded_prefix Public_key_hash.b58check_encoding "tz2" 36
let () = Base58.check_encoded_prefix b58check_encoding "sppk" 55
let () = Base58.check_encoded_prefix b58check_encoding "spsk" 54
let () = Base58.check_encoded_prefix b58check_encoding "spsig1" 99

P-256:
let () = Base58.check_encoded_prefix Public_key_hash.b58check_encoding "tz3" 36
let () = Base58.check_encoded_prefix b58check_encoding "p2pk" 55
let () = Base58.check_encoded_prefix b58check_encoding "p2sk" 54
let () = Base58.check_encoded_prefix b58check_encoding "p2sig" 98
